---

- name: Create directories for sites
  file:
    dest=/var/www/{{ item['server'] }}
    owner=www-data
    group=www-data
    state=directory
    mode=0775
  with_items: nginx_sites

- name: Create the configurations for sites
  template:
    src=site.j2
    dest=/etc/nginx/sites-available/{{ item['server'] }}
    owner=www-data
    group=www-data
    mode=0644
  with_items: nginx_sites
  notify:
   - restart nginx

- name: Create the configurations for proxies
  template:
    src=proxy.j2
    dest=/etc/nginx/sites-available/{{ item['server'] }}
    owner=www-data
    group=www-data
    mode=0644
  with_items: nginx_proxies
  notify:
   - restart nginx

- name: Enable the configurations for sites
  file:
    src=/etc/nginx/sites-available/{{ item['server'] }}
    dest=/etc/nginx/sites-enabled/{{ item['server'] }}
    state=link
  with_items: nginx_sites
  notify:
    - restart nginx

- name: Enable the configurations for proxies
  file:
    src=/etc/nginx/sites-available/{{ item['server'] }}
    dest=/etc/nginx/sites-enabled/{{ item['server'] }}
    state=link
  with_items: nginx_proxies
  notify:
    - restart nginx

