---

- hosts: all
  sudo: yes
  roles:
    - ubuntu
    - secure-vps
    - monitored

- hosts: database
  sudo: yes
  roles:
    - postgres

- hosts: appserver
  sudo: yes
  roles:
    - python
    - supervisor
    - nginx
    - redis

