- hosts: all
  sudo: True

  vars:
    postgres:
      superuser: diamond
      superuser_password: rBJAyLpHx8R4qZgPJE

  roles:
    - common
    - python
    - supervisor
    - role: nginx
      nginx_sites: none
    - postgres
    - redis
