---

- hosts: all
  sudo: yes
  roles:
    - debian

- hosts: database
  sudo: yes
  roles:
    - postgres

- hosts: appserver
  sudo: yes
  roles:
    - python
    - supervisor
    - nginx
    - redis

