---
- name: updates a server
  apt: update_cache=yes

- name: upgrade debian
  apt:
    upgrade=safe

- name: Install prerequisites
  apt:
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
    - python-apt
    - python-pycurl   # Not present on default installs, required for apt_repository
    - build-essential
    - git

- name: Add additional repositories
  apt_repository:
    repo='{{ item }}'
    update_cache=yes
    state=present
  with_items: debian_up2date.extra_repositories

- name: Set default release
  template:
    src=apt-default-release.j2
    dest=/etc/apt/apt.conf.d/99-default-release
    mode=0644

- name: Update packages
  apt:
    upgrade=safe
