---

- name: Compare kernel versions
  shell: grep "$(uname -v)" /boot/vmlinuz*
  sudo: yes
  ignore_errors: yes
  register: grep_result
  changed_when: grep_result.rc != 0

- name: Reboot machine
  command: reboot
  sudo: yes
  when: grep_result.rc != 0 and kernel_up2date == "boot"

- name: Wait for machine to come back
  local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port }} delay=5 timeout=300
  when: grep_result.rc != 0 and kernel_up2date == "boot"

- name: Wait a bit more
  pause: seconds=10
  when: grep_result.rc != 0 and kernel_up2date == "boot"

- name: Shutdown machine
  command: shutdown -h now
  sudo: yes
  when: grep_result.rc != 0 and kernel_up2date == "manual_boot"

- name: Wait for boot
  pause: "prompt='Please boot {{ inventory_hostname }} and press enter to continue'"
  when: grep_result.rc != 0 and kernel_up2date == "manual_boot"

- name: Wait for machine to come back
  local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port }} timeout=300
  when: grep_result.rc != 0 and kernel_up2date == "manual_boot"
