- name: install supervisor redhat/centos
  pip: name=supervisor state=latest

- name: ensure supervisor conf.d directory exists
  file:
    path: /etc/supervisor/conf.d
    state: directory

- name: ensure supervisor log directory exists
  file:
    path: /var/log/supervisor
    state: directory

- name: Copy supervisor global configuration
  copy: src=supervisord.conf dest=/etc/supervisor/supervisord.conf

- name: Install as service with automatic start on redhat/centos
  copy: src=supervisor dest=/etc/init.d/supervisord mode=0755 group=root owner=root

- name: Enable and run service
  service: name=supervisord state=started enabled=yes

