---
- name: updates a server
  apt: update_cache=yes

- name: upgrade ubuntu
  apt:
    upgrade=safe

- name: Install prerequisites
  apt:
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
    - python-apt
    - python-pycurl   # Not present on default installs, required for apt_repository
    - build-essential
    - git

- name: Update packages
  apt:
    upgrade=safe
