---

- name: Enable postgres access
  postgresql_user: name=postgres password={{ postgres_pwd }}

- name: Create databases
  postgresql_db:
    name={{ item }}
    encoding=UTF-8
    login_password={{ postgres_pwd }}
  with_items: databases

- name: Create database users
  postgresql_user:
    db={{ item }}
    name={{ item }}
    password={{ lookup('password', pwd_root + item + ' length=80') }}
    role_attr_flags=NOCREATEDB,NOCREATEROLE,NOCREATEUSER
    login_password={{ postgres_pwd }}
  with_items: databases

- name: Allow access for database users
  lineinfile:
    dest=/etc/postgresql/9.3/main/pg_hba.conf
    line="host{{ '\t' }}{{ item[0] }}{{ '\t' }}{{ item[0] }}{{ '\t' }}{{ item[1] }}{{ '\t' }}md5"
  with_nested:
    - databases
    - trusted_networks
  notify:
    - reload postgresql
