---

- name: install postgresql packages ubuntu
  apt: name={{ item }} state=latest
  with_items:
    - postgresql
    - postgresql-contrib
    - postgresql-client
    - python-psycopg2
    - libpq-dev

- name: Allow network access
  lineinfile:
    dest=/etc/postgresql/9.3/main/postgresql.conf
    regexp=listen_addresses
    line="listen_addresses = '*'"
  notify:
    - restart postgresql

- name: Start PostgreSQL
  service:
    name=postgresql
    state=started


