---

- name: install postgresql packages debian/ubuntu
  apt: pkg={{ item }} state=latest
  with_items:
    - postgresql
    - postgresql-contrib
    - postgresql-client
    - libpq-dev
    - python-psycopg2

- name: Allow network access
  lineinfile:
    dest=/etc/postgresql/9.1/main/postgresql.conf
    regexp=listen_addresses
    line="listen_addresses = '*'"
  notify:
    - restart postgresql

- name: Start PostgreSQL
  service:
    name=postgresql
    state=started


