- name: install postgresql packages debian/ubuntu
  apt: pkg={{ item }} state=latest
  with_items:
    - postgresql
    - postgresql-contrib
    - postgresql-client
    - libpq-dev
  when: ansible_os_family == "Debian"

- name: install postgresql python bindings
  pip: name=psycopg2

- name: grant access for sentry database to graphite user
  sudo_user: postgres
  postgresql_user:
    user: "{{ postgres.superuser }}"
    password: "{{ postgres.superuser_password }}"
    role_attr_flags: "CREATEDB,SUPERUSER"
    state: present
  when: postgres.superuser is defined